### ISSUE TITLE
"pgSetup" / "pg-test run" invoke migrations without setting DATABASE_URL

### ISSUE THREAD

**Issue by hawkrives** [ForbesLindesay/atdatabases#245]
In my sample code below, my `migrationsScript` is invoked without the `DATABASE_URL` environment variable being set.

```ts
import pgSetup from '@databases/pg-test/jest/globalSetup';
import pgTeardown from '@databases/pg-test/jest/globalTeardown';

jest.setTimeout(15000);

beforeAll(async () => {
	await pgSetup({ migrationsScript: ['env'], debug: true });
});

afterAll(async () => {
	await pgTeardown();
});

test('sets up a test database', async () => {
	// run a query against the database
});
```

Here is a sample of the terminal output:

```
[snipped]

  console.info
    Setting pg connection string on environment: DATABASE_URL

      at setup (node_modules/@databases/pg-test/src/jest/globalSetup.ts:28:11)

  console.info
    Running pg migrations

      at setup (node_modules/@databases/pg-test/src/jest/globalSetup.ts:31:13)

TERM_PROGRAM=iTerm.app
[omitted for privacy]
NODE_ENV=test
TS_JEST=1
JEST_WORKER_ID=1

pg-test
Error: No such container: pg-test
 PASS  test/migrations.e2e.spec.ts (9.985 s)
  ✓ sets up a test database (51 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        10.17 s
```

If I inspect `process.env` after `pgSetup` has returned, I have my `DATABASE_URL`.

I haven't found the bug in the code yet, but I was wondering if this was intentional behavior or not?

Please let me know if anything is unclear, and I'll respond!

**Comment by ForbesLindesay** [comment]
That looks like a bug to me. I would guess that something in how we call the migration script (https://github.com/ForbesLindesay/atdatabases/blob/master/packages/pg-test/src/jest/globalSetup.ts#L32-L46) is failing to pass in the environment variable. If you feel like having a go at a fix, I would really like to swap `modern-spawn` for `execa` (https://www.npmjs.com/package/execa) so you could make that change, and then it may fix the issue.
